language: php
os: linux

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.3
      dist: precise
      env:
        - BCMATH="off"
    - php: 5.4
      dist: trusty
    - php: 5.4
      dist: trusty
      env:
        - BCMATH="off"
    - php: 5.5
      dist: trusty
    - php: 5.5
      dist: trusty
      env:
        - BCMATH="off"
    - php: 5.6
    - php: 5.6
      env:
        - BCMATH="off"
    - php: 7.0
    - php: 7.0
      env:
        - BCMATH="off"
    - php: 7.1
    - php: 7.1
      env:
        - BCMATH="off"
    - php: 7.2
    - php: 7.2
      env:
        - BCMATH="off"
    - php: 7.3
    - php: 7.3
      env:
        - BCMATH="off"
    - php: 7.4
    - php: 7.4
      env:
        - BCMATH="off"

before_install:
  - if [[ $BCMATH == "off" ]]; then
        export PHP_BUILD_CONFIGURE_OPTS="--disable-bcmath";
        git clone git://github.com/php-build/php-build.git $HOME/.phpenv/plugins/php-build;
        travis_wait phpenv install --force `php -r "echo PHP_VERSION;"`;
        phpenv rehash;
        phpenv global `php -r "echo PHP_VERSION;"`;
    fi
  - php -i | grep bcmath

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - composer install -n

script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src tests --standard=psr2 -sp

after_script:
  - php vendor/bin/coveralls
